blog/urls.py
from django.urls import path, include
from blog import views

app_name = 'blog'

urlpatterns = [
    # 포스트 목록
    path('', views.index, name='index'),  #127.0.0.1:8000/blog/
    # 상세 페이지
    path('<int:post_id>/', views.detail, name='detail'),
    #카테고리
    path('category/<str:slug>/', views.category_page, name='category_page'),
    # 포스트 쓰기
    path('post/create/', views.post_create, name='post_create'),
]

common/urls.py
from django.urls import path, include
from blog import views
from django.contrib.auth import views as auth_views

app_name = 'common'

urlpatterns = [
    #로그인
    path('login/', auth_views.LoginView.as_view(
      template_name = 'common/login.html'), name='login'),
    #로그아웃
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from blog import views

urlpatterns = [
    path('', views.index),    #127.0.0.1:8000/
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('common/', include('common.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.contrib.auth.models import User
from django.db import models

class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)  #카테고리 이름
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)  #한글인코딩

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return "/blog/category/{}".format(self.slug)

    class Meta:
        verbose_name_plural = 'Categories'


# Post 모델
class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    pub_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    photo = models.ImageField(upload_to='blog/images/%Y/%m/%d/',
                              null=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, null=True, blank=True, on_delete=models.SET_NULL)
    # 카테고리가 삭제되어도 블로그는 유지됨(미분류가 있을수 있다.)

    def __str__(self):
        return self.title

common/models.py
from django.db import models

# Create your models here.

blog/forms.py
from django import forms
from blog.models import Post

# 포스트 등록 폼
class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content', 'photo', 'category']
        labels = {
            'title': '제목',
            'content': '내용',
            'photo': '사진',
            'category': '카테고리'
        }

blog/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404,redirect
from django.utils import timezone
from blog.forms import PostForm
from blog.models import Post, Category


def index(request):
    # 포스트 목록
    post_list = Post.objects.order_by('-pub_date')  #최근 작성일 -내림차순
    categories = Category.objects.all()
    context = {'post_list': post_list, 'categories': categories}
    return render(request, 'blog/post_list.html', context)

def detail(request, post_id):
    # 상세 페이지
    post = get_object_or_404(Post, pk=post_id)
    # post = Post.objects.get(id=post_id)   #포스트 1개 가져오기
    categories = Category.objects.all()
    context = {'post': post, 'categories': categories}
    return render(request, 'blog/post_detail.html', context)

def category_page(request, slug):
    #카테고리
    category = Category.obfects.get(slug=slug)
    post_list = Post.objects.filter(category=category)
    categories = Category.objects.all()
    context = {
        'category': category,
        'post_list': post_list,
        'categories': categories
    }
    return render(request, 'blog/post_list.html', context)

@login_required(login_url='common:login')
def post_create(request):
    #포스트 쓰기
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.pub_date = timezone.now()
            post.author = request.user     #작성자
            post.save()  #db에 저장
            return redirect('blog:index')
    else:
        form = PostForm()
    context = {'form':form}
    return render(request, 'blog/post_form.html', context)

common/views.py
from django.shortcuts import render

# Create your views here.

templates/blog/post_detail.html
<!DOCTYPE html>
<html lang="ko">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>{{ post.title }} - Blog</title>
</head>
<body>
    <div id="container">
       {% include 'navbar.html' %}
        <section id="detail">
             <h3>{{ post.title }}</h3>
             <h5>작성자:{{ post.author }} (작성일:{{ post.pub_date }})</h5>
                {% if post.photo %}
                    <img src="{{ post.photo.url }}">
                {% endif %}
             <p>{{ post.content | linebreaks }}</p>
        </section>
        <aside>
            <h3>분류(Categories)</h3>
            <div>
                {% for category in categories %}
                <li>
                    <a href="{{ category.get_absolute_url }}">
                    {{ category }}({{ category.post_set.count }})</a>
                </li>
                {% endfor %}
            </div>
        </aside>
    </div>
</body>
</html>

templates/blog/post_form.html
<!DOCTYPE html>
<html lang="ko">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>Blog</title>
    <link rel="stylesheet" href="{% static 'blog/css/style.css' %}">
</head>
<body>
<div id="container">
    {% include 'navbar.html' %}
    <section>
        <h1>글쓰기</h1>
        <form action="" method="post" enctype="multipart/form-data">
            <!--  일반 필드와 파일(이미지)필드 멀티로 구성됨  -->
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">저장하기</button>
        </form>

    </section>
</div>
</body>
</html>

templates/blog/post_list.html
<!DOCTYPE html>
<html lang="ko">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>Blog</title>
    <link rel="stylesheet" href="{% static 'blog/css/style.css' %}">
</head>
<body>
    <div id="container">
       {% include 'navbar.html' %}
        <section id="list">
            <h1>블로그 홈 입니다.</h1>
            {% if post_list %}
                {% for post in post_list %}
                    <hr>
                    <h3><a href="{% url 'blog:detail' post.id %}">{{ post.title }}</a></h3>
                    <h5>작성자:{{ post.author }} (작성일:{{ post.pub_date }})</h5>
                        {% if post.photo %}
                            <img src="{{ post.photo.url }}">
                        {% endif %}
                    <p>{{ post.content | linebreaks }}</p>
                {% endfor %}
            {% else %}
                <p>포스트가 없습니다.</p>
            {% endif %}
        </section>
         <aside>
            <h3>분류(Categories)</h3>
            <div>
               {% for category in categories %}
                <ul>
                    <li>
                        <a href="{{ category.get_absolute_url }}">
                        {{ category }}({{ category.post_set.count }})</a>
                    </li>
                </ul>
                {% endfor %}
            </div>
        </aside>
    </div>
</body>
</html>

templates/common/login.html
<!DOCTYPE html>
<html lang="ko">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>Blog</title>
    <link rel="stylesheet" href="{% static 'blog/css/style.css' %}">
</head>
<body>
<div id="container">
    {% include 'navbar.html' %}
    <section>
        <h1>로그인</h1>
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">로그인</button>
        </form>

    </section>
</div>
</body>
</html>

templates/navbar.html
 <header>
    <nav>
        <ul>
            <li><a href="{% url 'blog:index' %}">Home</a></li>
            <li><a href="{% url 'blog:post_create' %}">글쓰기</a></li>
            {% if user.is_authenticated %}
                 <li><a href="{% url 'common:logout' %}">({{ user.username }})로그아웃</a></li>
            {% else %}
                 <li><a href="{% url 'common:login' %}">로그인</a></li>
            {% endif %}
        </ul>
    </nav>
</header>